# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    client_host: '%env(string:CLIENT_HOST)%'
    lifetime_account_activation_url: '%env(int:LIFETIME_ACCOUNT_ACTIVATION_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $host: '%client_host%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Nurschool\Notifier\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    _instanceof:
        Nurschool\Common\Domain\Event\DomainEventListener:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    SendGrid:
        class: \SendGrid
        arguments: [ '%nurschool_sendgrid.api_key%' ]

    Nurschool\Notifier\Infrastructure\Mailer\Sendgrid\Provider\SendgridProvider:
        arguments:
            - '@SendGrid'
            - '@Nurschool\Notifier\Infrastructure\Symfony\Sendgrid\SymfonySendgridEventDispatcher'
            - '%nurschool_sendgrid.disable_delivery%'
            - '%nurschool_sendgrid.sandbox%'

    Nurschool\Notifier\Infrastructure\Mailer\Sendgrid\SendgridMailer:
        arguments:
            - '@Nurschool\Notifier\Infrastructure\Mailer\Sendgrid\Provider\SendgridProvider'
            - '%nurschool_sendgrid.emails%'

    Nurschool\Common\Infrastructure\Url\UriSigner:
        arguments: 
            - '%kernel.secret%'
            - 'signature'

    Nurschool\Common\Application\Url\SignService:
        arguments:
            - '%kernel.secret%'
            - '@Nurschool\Common\Infrastructure\Url\UriSigner'

    Nurschool\Notifier\Application\Bus\Event\UserWasCreatedEventListener:
        arguments:
            $lifetime: '%lifetime_account_activation_url%'